<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Stable Diffusion Plugin</text>

        <Action name="txt2img">
            <icon/>
            <text>Apply txt2img</text>
            <whatsThis/>
            <toolTip/>
            <iconText/>
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>ctrl+alt+q</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip/>
        </Action>
        <Action name="img2img">
            <icon/>
            <text>Apply img2img</text>
            <whatsThis/>
            <toolTip/>
            <iconText/>
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>ctrl+alt+w</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip/>
        </Action>
        <!--
        <Action name="img2img_upscale">
            <icon/>
            <text>Apply SD upscale transform</text>
            <whatsThis/>
            <toolTip/>
            <iconText/>
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>ctrl+alt+e</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip/>
        </Action>
        -->
        <Action name="img2img_inpaint">
            <icon/>
            <text>Apply img2img inpaint</text>
            <whatsThis/>
            <toolTip/>
            <iconText/>
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>ctrl+alt+r</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip/>
        </Action>
        <Action name="prepare_inpaint">
            <icon/>
            <text>"Add inpaint layer and switch brush"</text>
            <whatsThis/>
            <toolTip/>
            <iconText/>
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>ctrl+alt+a</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip/>
        </Action>
        <Action name="paint_ext_interrupt">
            <icon/>
            <text>Interrupt image generation</text>
            <whatsThis/>
            <toolTip/>
            <iconText/>
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>ctrl+alt+i</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip/>
        </Action>
        <Action name="simple_upscale">
            <icon/>
            <text>Apply simple upscaler</text>
            <whatsThis/>
            <toolTip/>
            <iconText/>
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>ctrl+alt+t</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip/>
        </Action>
    </Actions>
</ActionCollection>